### ISSUE TITLE
Allow config file to be stored on explicit full path location

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/SBS#389]
https://github.com/SURFscz/SBS/blob/9bc922484eb0fc8022e5595e0a5fb6f23bdcb5af/server/tools.py#L11

At this moment the Config file is always relative to the main module base location. If you want to reference an Config file to be stored in /etc/sbs for example, you can't.

Suggestion to not add prefix of module base location if the CONFIG environment variable starts with a '/'.

**Comment by baszoetekouw** [comment]
Why would you want this?

**Comment by baszoetekouw** [comment]
@HarryKodden why is this needed?

**Comment by HarryKodden** [comment]
Question was raised when running SBS in Docker Container where you want to mount the application Root Path to a Host Folder location and overwrite the ../server/config/myconfig.yml with your own configuration.
The way I do it right now is very hackish....

docker-compose.yml:
```
  server:
    build: server
    restart: "always"
    links:
      - db
      - redis
    volumes:
      - ${PWD}/etc/config.yml:/etc/config.yml
      - ${PWD}/server:/opt/server
    ports:
      - 8080
    environment:
      CONFIG_TEMPLATE: /etc/config.yml
```


startup:
```
    CMD [ "/bin/bash", "-c", \
  "envsubst <${CONFIG_TEMPLATE:-server/config/test_config.yml} >server/${CONFIG}; uwsgi --socket 0.0.0.0:8080 --protocol=http --module server.__main__:app;" \
  ]
```
