### ISSUE TITLE
Make SCIM schema URNs configurable

### ISSUE THREAD

**Issue by arnoutt** [SURFscz/SBS#497]
We now use hardcoded `urn:mace:surf.nl:sram:scim:`, but that should probably not be hardcoded, but configurable in a file, so it can be changed for different instances of the SBS repository.

**Comment by HarryKodden** [comment]
@baszoetekouw My advice is to keep this as is.

**Comment by baszoetekouw** [comment]
@HarryKodden why?  
I don't think @arnoutt is asking for us to change the currently value, but merely to move the hardcoded base `urn:mace:surf.nl:sram:` to config instead of code.  And I think that makes sense, because we want SBS to be easily reusable.

**Comment by logan-life** [comment]
We decided this would be nice to do and not a big lift, so go for it.

**Comment by HarryKodden** [comment]
Feature implemented, 
In config.yml new key is added that may hold the desired key for the SRAM extension attributes:
```
scim_schema_sram: "urn:mace:surf.nl:sram:scim:extension"
```

**Comment by mrvanes** [comment]
Everything seems to work correct.

Too bad we now have two top-level keys referring to scim instead of one:
```
scim_sweep:
  # Do we enable scim sweeps?
  enabled: True
  # How often do we check if scim sweeps are needed per service
  cron_minutes_expression: "*/15"

scim_schema_sram: "urn:mace:example.com:sram:scim:extension"
```
Would be nice to merge them one day.
